// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4EIT4F8gLxIoAzd7K7yYHfMsqeFQo98',
    appId: '1:43636374258:web:84f48364ea83a3e9af6e6b',
    messagingSenderId: '43636374258',
    projectId: 'my-mr-grp-project',
    authDomain: 'my-mr-grp-project.firebaseapp.com',
    storageBucket: 'my-mr-grp-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZN-Nn1ku2XgINwtFzxraFkMaz4sl1Qk',
    appId: '1:43636374258:android:8627818bced2b071af6e6b',
    messagingSenderId: '43636374258',
    projectId: 'my-mr-grp-project',
    storageBucket: 'my-mr-grp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo44uaSx_emRhSPOUiZUyKGLZIBXq7zoc',
    appId: '1:43636374258:ios:acc3963bb75d9e5aaf6e6b',
    messagingSenderId: '43636374258',
    projectId: 'my-mr-grp-project',
    storageBucket: 'my-mr-grp-project.appspot.com',
    iosClientId: '43636374258-0pn1f551lr5pb5ns93eh3mmjtvf52919.apps.googleusercontent.com',
    iosBundleId: 'com.mrgroup.authentication',
  );
}
